# Generated by Django 6.0.1 on 2026-06-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('pl', 'Polish')], default='en', help_text='Preferred language for translations', max_length=10),
        ),
    ]
