# Generated by Django 5.1.15 on 2026-06-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', 'email']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('north_america', 'North America'), ('south_america', 'South America'), ('europe', 'Europe'), ('asia', 'Asia'), ('africa', 'Africa'), ('oceania', 'Oceania'), ('middle_east', 'Middle East')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('pl', 'Polish')], default='en', max_length=10),
        ),
    ]
