# Generated by Django 6.0.1 on 2026-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='position',
            field=models.PositiveBigIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
