# Generated by Django 6.0.1 on 2026-06-05 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_message_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source_language',
            field=models.CharField(blank=True, help_text='Detected language of the message', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='MessageTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_language', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chat_messages.message')),
            ],
            options={
                'indexes': [models.Index(fields=['message', 'target_language'], name='chat_messag_message_9fbcc7_idx')],
                'unique_together': {('message', 'target_language')},
            },
        ),
    ]
