# Generated by Django 6.0.1 on 2026-05-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='direct_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
