# Generated by Django 6.0.1 on 2026-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_direct_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='last_read_position',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
