# Generated by Django 6.0.1 on 2026-06-01 13:27

import apps.chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatmember_last_read_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.chats.models.chat_avatar_path),
        ),
    ]
